name: Packer build

on:
  push:
    branches: [main]

env:
  HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://hetzner.cloud/?ref=72AtIaBWO7Uw  # 🤡
    steps:
      - name: Install Butane
        run: |
          podman create --name butane quay.io/coreos/butane:release
          podman cp butane:/usr/local/bin/butane /usr/local/bin/
          podman rm -f butane

      - name: Check toolchain versions
        run: butane --version; packer version

      - uses: actions/checkout@v4

      - name: packer init
        run: packer init .

      - name: packer build
        run: packer build .
